### ISSUE TITLE
Execution failed for task ':device_apps:verifyReleaseResources'.

### ISSUE THREAD

**Issue by mohitjadav** [g123k/flutter_plugin_device_apps#23]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'device_apps'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

The plugin device_apps could not be built due to the issue above.

**Comment by g123k** [comment]
Hello,

I close your ticket, because it's not related to this Flutter plugin.
But in your project, you have to edit the `android/local.properties` file.

Please ensure you have define the constant `sdk.dir` which contains the path to your local Android SDK. Eg:

`sdk.dir=/Users/g123k/Library/Android/sdk`

**Comment by mohitjadav** [comment]
its not working

**Comment by g123k** [comment]
It is still the same error?
