### ISSUE TITLE
[Feature request] Detect changes in apps list.

### ISSUE THREAD

**Issue by bimsina** [g123k/flutter_plugin_device_apps#58]
Is there any way to trigger getInstalledApplications() once an app is removed or installed?

One way is to create a periodic function to get the apps but I don't think that's a good idea.

**Comment by faisalansari0367** [comment]
this is also my question once i get all of the installed apps how do i detect changes if another app is installed by the user how do i get that app information without running getInstalledApplication because it's a heavy operation if a user has 300 or 400 apps its a very heavy resource operation to run this method again & again...hope someone will ans our questions...

**Comment by g123k** [comment]
I add this to feature to my TODO list :)

**Comment by faisalansari0367** [comment]
Hey I want one more thing I want to create a file observer who watches
recursively for file changes and receive events to the dart and this work
needs to be done in background please help me about this. I have
implemented a file observer but it's just watching the root path not the
whole file system I have made a plugin storage_details there I implemented
this you can check if you want.

**Comment by g123k** [comment]
Don't worry, I already how to write the feature ;)

**Comment by g123k** [comment]
It's now available in the 1.3.0 release
